DROP DATABASE IF EXISTS FLOWERAPP;
CREATE DATABASE IF NOT EXISTS FLOWERAPP;
USE FLOWERAPP;
-- Crear la tabla categoria toxicologica para productos
DROP TABLE IF EXISTS CategoriaToxicologica;
CREATE TABLE IF NOT EXISTS CategoriaToxicologica (
  PK_CATEGORIATOXICOLOGICA INT PRIMARY KEY AUTO_INCREMENT,
  CT_Nomenclatura CHAR(4) NOT NULL UNIQUE,
  CT_Descripcion VARCHAR(250) NOT NULL UNIQUE
);
-- Crear la tabla Unidades
DROP TABLE IF EXISTS Unidad;
CREATE TABLE IF NOT EXISTS Unidad (
  PK_UNIDAD INT PRIMARY KEY AUTO_INCREMENT,
  U_Nombre VARCHAR(50) NOT NULL UNIQUE,
  U_Nomenclatura VARCHAR(10) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS Producto;
CREATE TABLE IF NOT EXISTS Producto(
  PK_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
  P_Stock INT NOT NULL,
  P_Codigo VARCHAR(50) NOT NULL UNIQUE,
  P_Nombre VARCHAR(255) NOT NULL,
  P_ContenidoUnitario INT NOT NULL,
  /*Esta columna se puede agregar opcionalmente de ser necesario*/
  -- P_ContenidoRestante INT NOT NULL,
  P_FechaCompra DATE NOT NULL,
  P_Descripcion VARCHAR(255) NOT NULL,
  FK_UNIDAD INT NOT NULL,
  FK_CATEGORIATOXICOLOGICA INT NOT NULL,
  FOREIGN KEY (FK_UNIDAD) REFERENCES Unidad(PK_UNIDAD),
  FOREIGN KEY (FK_CATEGORIATOXICOLOGICA) REFERENCES CategoriaToxicologica(PK_CATEGORIATOXICOLOGICA)
);

DROP TABLE IF EXISTS TipoAplicacion;
CREATE TABLE IF NOT EXISTS TipoAplicacion (
  PK_TIPOAPLICACION INT PRIMARY KEY AUTO_INCREMENT,
  TA_Tipo VARCHAR(50) NOT NULL UNIQUE,
  TA_Descripcion VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS DetallesGeneralesAplicacion;
CREATE TABLE IF NOT EXISTS DetallesGeneralesAplicacion (
  PK_DETALLES_GENERALES INT PRIMARY KEY AUTO_INCREMENT,
  DGA_FechaAplicacion DATE NOT NULL,
  DGA_TotalAgua INT NOT NULL,
  DGA_Descripcion VARCHAR(255) NOT NULL,
  FK_TIPOAPLICACION INT NOT NULL,
  FOREIGN KEY (FK_TIPOAPLICACION) REFERENCES TipoAplicacion(PK_TIPOAPLICACION)
);

DROP TABLE IF EXISTS DetallesProductoAplicado;
CREATE TABLE IF NOT EXISTS DetallesProductoAplicado (
  PK_DETALLESPRODUCTOAPLICADO INT PRIMARY KEY AUTO_INCREMENT,
  DPA_TotalProductoUsado DECIMAL(10,2) NOT NULL,
  DPA_TotalProductoUsadoRedondeado DECIMAL(10,2),
  FK_PRODUCTO INT NOT NULL,
  FK_DETALLES_GENERALES INT NOT NULL,
  FOREIGN KEY (FK_PRODUCTO) REFERENCES Producto(PK_PRODUCTO),
  FOREIGN KEY (FK_DETALLES_GENERALES) REFERENCES DetallesGeneralesAplicacion(PK_DETALLES_GENERALES)
);
